# find_duplicates.ps1
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$PSScriptRoot = if ($PSScriptRoot) { $PSScriptRoot } else { (Get-Location).Path }
$LogFile = Join-Path -Path $PSScriptRoot -ChildPath "find_duplicates_log_$(Get-Date -Format 'yyyyMMdd_HHmmss').txt"
Start-Transcript -Path $LogFile -Force

try {
    Write-Host "Starting duplicate file search in '$PSScriptRoot'..."
    Write-Host "Excluding directories: node_modules, .git"

    $files = Get-ChildItem -Path $PSScriptRoot -Recurse -File | Where-Object {
        $_.FullName -notmatch "[\\/](node_modules|.git)[\\/]"
    }

    Write-Host "Found $($files.Count) files to analyze. Calculating hashes..."

    # Use a progress bar for hashing
    $counter = 0
    $totalFiles = $files.Count
    $hashes = $files | ForEach-Object {
        $counter++
        Write-Progress -Activity "Calculating Hashes" -Status "Processing file $counter of $totalFiles" -PercentComplete (($counter / $totalFiles) * 100)
        Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256
    }
    
    $duplicates = $hashes | Group-Object -Property Hash | Where-Object { $_.Count -gt 1 }

    if ($duplicates.Count -eq 0) {
        Write-Host "No duplicate files found." -ForegroundColor Green
        return
    }

    Write-Host "Found $($duplicates.Count) set(s) of duplicate files." -ForegroundColor Yellow

    $deletionScriptPath = Join-Path -Path $PSScriptRoot -ChildPath "delete_duplicates.ps1"
    $deletionCommands = @()
    $deletionCommands += "# This script was generated by find_duplicates.ps1 on $(Get-Date)"
    $deletionCommands += "# Review the files below carefully before running this script."
    $deletionCommands += ""

    foreach ($group in $duplicates) {
        # Sort by path length to prefer keeping shorter/root paths
        $sortedGroup = $group.Group | Sort-Object { $_.Path.Length }
        $original = $sortedGroup | Select-Object -First 1
        $duplicateFiles = $sortedGroup | Select-Object -Skip 1

        $deletionCommands += "# --- Duplicate Set (Hash: $($original.Hash)) ---"
        $deletionCommands += "# KEEPING: $($original.Path)"
        Write-Host "---"
        Write-Host "Keeping: $($original.Path)" -ForegroundColor Green

        foreach ($dup in $duplicateFiles) {
            $deletionCommands += "Remove-Item -LiteralPath '$($dup.Path)' -Verbose"
            Write-Host "  Found duplicate: $($dup.Path)" -ForegroundColor Yellow
        }
        $deletionCommands += ""
    }

    [System.IO.File]::WriteAllLines($deletionScriptPath, $deletionCommands)

    Write-Host "---"
    Write-Host "IMPORTANT:" -ForegroundColor Cyan
    Write-Host "A script to delete the duplicate files has been created at:" -ForegroundColor Cyan
    Write-Host "$deletionScriptPath" -ForegroundColor Cyan
    Write-Host "Please REVIEW this script carefully. If you are sure, run it manually from the terminal to delete the files." -ForegroundColor Cyan
    Write-Host "No files have been deleted yet." -ForegroundColor Cyan

}
catch {
    Write-Host "An error occurred: $($_.Exception.Message)" -ForegroundColor Red
}
finally {
    Stop-Transcript
    Write-Host "Log file created at: $LogFile"
}
